### PR TITLE
14 skins (v2 Skin update)

### PR DESCRIPTION
**Pull request by ColoredHue**
Added skins:
* Aerial
* Aztec
* Bomb Boy
* Bone Dragon
* Cooler Carl
* Crabby
* Danger
* Dragonfly
* Lunar
* Neo
* Pixel
* Rose
* Shell
* Stained Glass

### CODE REVIEW

**Comment by codergautam** [comment]
Omg what a legend

**Comment by codergautam** [comment]
You added some skin images but I dont see reference to them on the json (example: baa)

**Comment by ColoredHue** [comment]
its fine they were just extra

**Comment by ColoredHue** [comment]
Edit: added new skins into other cosmetics.json files
should be fine now

**Pull request merged**
